apiVersion: v1
kind: Secret
metadata:
  name: mysql
  labels:
    project: roboshop
    environment: dev
    tier: database
    component: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD:  "Um9ib1Nob3BAMQ=="
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mysql
  namespace: roboshop
  # deployment labels
  labels:
    project: roboshop
    environment: dev
    tier: database
    component: mysql
spec:
  replica: 1
  # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      tier: database
      component: mysql
  # This is pod definition
  template:
    metadata:
      labels: 
        project: roboshop
        environment: dev
        tier: database
        component: mysql
    spec:
      containers:
      - name: mysql
        image: kranthikumar96/mysql:v1
        envFrom:
        - secretRef:
          name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tier: database
    component: mysql
spec:
  selector:
    project: roboshop
    environment: dev
    tier: database
    component: mysql
  ports:
  - protocol: TCP
    port: 3306  # service port
    targetport: 3306  # container port